---

- name: Load variables for the target system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "os/{{ ansible_distribution }}.yml"
        - "os/{{ ansible_os_family }}.yml"
      skip: true

- name: Install asdf version manager
  ansible.builtin.include_tasks: install.yml

- name: Initialise shell
  ansible.builtin.include_tasks: shell.yml
  when: asdf_init_shell | bool

- name: Install plugins and packages
  ansible.builtin.include_tasks: plugins.yml
  when: asdf_plugins|length > 0
